version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--save", "20", "1"]
    volumes: 
      - redis-volume:/redis/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./configs/redis/users.acl:/usr/local/etc/redis/users.acl
  api:
    build: .
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "3011-3012:3005"
      - "50057-50058:50051"
    depends_on:
      - redis
  
  nginx:
    image: nginx
    volumes:
    - ./configs/templates/nginx:/etc/nginx/templates
    ports:
    - "10006:80"
    environment:
    - HOST_API=${HOST_API}
    depends_on:
      - api

  nginxGRPC:
    image: nginx
    volumes:
      - ./configs/templates/nginxGRPC:/etc/nginx/templates
      - ./configs/tls:/etc/nginx/certs
    ports:
      - "10007:1443"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

volumes:
  redis-volume:
    driver: local
networks:
  default:
    name: indefinite-studies-feed-builder-service-network