version: "3.9"
services:
  # TODO: clean, redis is deprecated
  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - '6379:6379'
  #   command:
  #     [
  #       "redis-server",
  #       "/usr/local/etc/redis/redis.conf",
  #       "--save",
  #       "20",
  #       "1"
  #     ]
  #   volumes:
  #     - redis-volume:/redis/data
  #     - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #     - ./configs/redis/users.acl:/usr/local/etc/redis/users.acl

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./configs/mongodb/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo_admin_password
      - MONGO_INITDB_DATABASE=feeddb

  api:
    build: .
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "3011-3012:3005"
      - "50057-50058:50051"
    depends_on:
      - redis
      - mongo

  nginx:
    image: nginx
    volumes:
      - ./configs/templates/nginx:/etc/nginx/templates
    ports:
      - "10006:80"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

  nginxGRPC:
    image: nginx
    volumes:
      - ./configs/templates/nginxGRPC:/etc/nginx/templates
      - ./configs/tls:/etc/nginx/certs
    ports:
      - "10007:1443"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

volumes:
  # TODO: clean, redis is deprecated
  redis-volume:
    driver: local
  mongo-volume:
    driver: local
networks:
  default:
    name: indefinite-studies-feed-builder-service-network
